### ISSUE TITLE
3.x.x deleting several folders (at least on Windows)

### ISSUE THREAD

**Issue by iNaD** [benkiefer/ember-cli-gradle-plugin#17]
Hi,

after several tests and applying my `port` patch to version `2.4.0`, I have to say that 3.x can't be used on Windows.

Folders are deleted (some in `node_modules`. `bower_components` and also `tests` and `app/templates`, hard to track the non git tracked files). Causing the tests (and the whole build) to fail.

Using `2.4.0` with my patch works fine as it did before, so it seems to be related to the changes you applied to the 3.x releases.

**Comment by benkiefer** [comment]
Can you please send some information about your build process? What terminal are you using? What version of Windows?

I've done testing on Windows 10 with version 3.0.0.

**Comment by iNaD** [comment]
Hmm maybe it's related to npm v3? I'll test it today and see if this caused the port thing, too.

**Edit:**

I tried it on my pc at work with npm 3.8.3 and node 5.7.1 and it works as intended with the ember-cli-gradle-plugin 3.0.0 (with --test-port having a value of -1). I'll have to inspect this further on my home pc. Maybe it is a bug caused by a different version of gradle or something similar.

Thanks for your effort anyway ;)

**Comment by iNaD** [comment]
So it seems that updating node and stuff wasn't very smart. Using the LTS version (which also runs on my work PC) everything works as intended. Maybe there should be a note that this weird behaviour can happen with newer Node versions.

**Comment by benkiefer** [comment]
Thanks for the update. I will take a look at the node issue and see what the behavior is without the plugin, since it just executes the ember commands. If the strange behavior is reproducible without the plugin I'll escalate up to the Ember folks.

**Comment by iNaD** [comment]
Hmm I'm not 100% sure, but this only seems to happen with recent versions of the VCS Tool [Source Tree](https://www.sourcetreeapp.com/), running in the background. Since I don't use it anymore / close it before building, this behavior didn't appear again.

In general it's causing weird things on multiple devices since some time. I think we can close this issue for now.

**Comment by benkiefer** [comment]
Thanks for following up @iNaD
