### ISSUE TITLE
ember serve instead of ember build

### ISSUE THREAD

**Issue by albertpak** [benkiefer/ember-cli-gradle-plugin#19]
is there a way to specify for this plugin to run `ember serve` instead of doing `ember build`?

**Comment by benkiefer** [comment]
I can allow you to configure the build command. Should be able to have something for you to try out later tonight.

**Comment by albertpak** [comment]
@benkiefer great :) thank you

**Comment by benkiefer** [comment]
@albertpak, can take a look at version 3.2.0? It should do what you need.

The README explains the changes that you will need to configure the build command, but to sum up, your configuration should look something like:

```
embercli {
     buildCommand = "serve"
    buildArguments = ["--environment==test"] // or whatever
}
```

**Comment by albertpak** [comment]
will test it out in a few - I was on `v3.0.0`

**Comment by albertpak** [comment]
Switched over to `v3.2.0` - looks like it does what its suppose, but "reload" part takes awhile.

The other "issue" that I see is that when server is running on `serve` command, it halts spring server from booting up

I see following warning in my console:
```
[WARN] `assets/vendor.js` took: 22485ms (more than 20,000ms)
```
Does it actually run `ember server` or does it run `ember build --watch`?

**Comment by benkiefer** [comment]
There is no translation on the plugins part. It will do exactly what you tell it to do.

**Comment by benkiefer** [comment]
Can you explain what you are trying to accomplish? Or share the project you are working on. That might help me figure out a better way to organize things for you.

**Comment by albertpak** [comment]
_I'm not familiar how Java projects work_, but this project has Spring server, and a client is using EmberJS - so they're using Gradle to do a build. So whenever I run a command to boot up the server, it runs this plugin also.

What I was looking for to do is to run a boot up command to start up the server and at the same time to start up the ember server also, and while in dev, to have a live reload option on ember enabled.

Hopefully that clears it up, wish i could share, but it's a client project.

**Comment by benkiefer** [comment]
The next thing you will need to figure out is who is serving the ember app. If it's being served by the java app, then it may look like the gradle-ember-cli-example project that I put up.

**Comment by benkiefer** [comment]
Here's a link to that project: https://github.com/benkiefer/gradle-ember-cli-example

**Comment by albertpak** [comment]
thank you :) will check it out

**Comment by albertpak** [comment]
went through your example app - and I have mine configured same way

`bootRun` runs and does the build, but then gets stuck on this line
```
> Building 36% > :client:emberBuild
```

**Comment by benkiefer** [comment]
The reason you are seeing the build hang after switching to ember serve is because of how ember serve works. It starts a little express app that runs on port 4200. It then blocks, so you will never get through the emberBuild step. I think what you are going to want to do is run with the default config and do your bootRun command.

If your app is configured like my example, bootRun will start your spring boot app on 8080, and you can browse to localhost:8080 and see your ember application being served by Spring.

I made a couple of updates to that example project tonight (because of some thymeleaf errors), so if you pull that project again, you should be able to have it running in a couple of minutes. Hope this helps!

**Comment by albertpak** [comment]
Thank you
