### ISSUE TITLE
Create 'environment' property for emberBuild task

### ISSUE THREAD

**Issue by admiral-diver** [benkiefer/ember-cli-gradle-plugin#7]
Hello, Ben Kiefer.

Is it possible to make string `-prod` as property of `grade.build` file? 
This improvement will help us to set not only `-prod` option but also `-test` and `-dev`.

**File: File: EmberCliPlugin.groovy**

```
111 args "build", "-prod"
```

Best regards,
Viacheslav.

**Comment by benkiefer** [comment]
I didn't need anything other prod yet, but expected to eventually, and my plan was to do something like:

```
 ext {
      ember {
           buildEnv = "production"
      }
 }
```

This would allow you to also override it with a command line param.

```
 ext {
      ember {
           buildEnv = project.getProperty('ember.environment') ?: "production"
      }
 }

gradlew build -Pember.environment=dev
```

Do you think this would work for you? I'll include an example in the sample project.

**Comment by benkiefer** [comment]
If that works, I will take a swing at this tonight.

**Comment by admiral-diver** [comment]
This is excellent solution. Thanks) I'll wait for it!

**Comment by benkiefer** [comment]
Alright, you should be good to go @admiral-diver. Go ahead and try out version 1.0.8. The README file has documentation on what you need to do (what we discussed above). Thanks for the request!

**Comment by benkiefer** [comment]
Correction, it is slightly different.

```
 apply plugin: "com.kiefer.gradle.embercli"
 embercli {
      environment = "development"
 }
```

**Comment by admiral-diver** [comment]
Thanks for the replay!)
